conda_forge_output_validation: true
conda_build_tool: rattler-build
noarch_platforms: linux_64
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test: native
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
